FROM debian:sid

RUN \
  apt-get update && \
  apt-get install -y openjdk-8-jre wget

ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64

RUN \
  mkdir -p /var/otp && \
  wget -O /var/otp/otp.jar https://repo1.maven.org/maven2/org/opentripplanner/otp/1.2.0/otp-1.2.0-shaded.jar && \
  wget -O /var/otp/jython.jar http://search.maven.org/remotecontent?filepath=org/python/jython-standalone/2.7.0/jython-standalone-2.7.0.jar

ENV OTP_BASE /var/otp
ENV OTP_GRAPHS /var/otp/graphs

RUN \
  mkdir -p /var/otp/scripting && \
  mkdir -p /var/otp/graphs/dk && \
  wget -O /var/otp/graphs/dk/ddot.zip https://navitia.opendatasoft.com/explore/dataset/dk/files/ec2e817b5b7462f54dc0f93793638ea5/download/ && \
  java -Xmx2G -jar /var/otp/otp.jar --build /var/otp/graphs/dk

EXPOSE 8080
EXPOSE 8081

ENTRYPOINT [ "java", "-Xmx2G", "-Xverify:none", "-cp", "/var/otp/otp.jar:/var/otp/jython.jar", "org.opentripplanner.standalone.OTPMain" ]

CMD [ "--help" ]
